cmd/testdata.go: Make bucket name configurable
storj/up pull request #77
Opened 2023-03-16 01:00 UTC by littleskunk

WIP

I want to give a customer 2 buckets. One with value attribution and one without. I had to modify the code for that. With this code change I am able to specify the bucket name and just call the command twice.

Still missing is the value attribution. I hope someone can pick up this pull request and finish that part.

2023-03-22 18:57 UTC, storj-antonio requested changes
I like the idea of putting all the string parameters together but I'm not sure if that will break any existing code that isn't using named return parameters. For instance, where previous code is expecting the usage period to be the third value returned where now it will be the 5th. Also expect that there would be datatype issues as the receiver would expect a time value type and will receive a string.

2023-03-22 18:57 UTC, storj-antonio commented on cmd/testdata.go
> +			return generateProjectUsage(database, email, bucket, valueattr, usagePeriod)
Is there anywhere in code that is uses this return, I believe you want to append the 2 new variables to the end of the function call, in this case after usage period. For instances where someone uses just the position instead of using named return paramaters.

2023-03-23 11:43 UTC, littleskunk commented on cmd/testdata.go
> +			return generateProjectUsage(database, email, bucket, valueattr, usagePeriod)
There is no other call in the code.

2023-03-23 11:46 UTC, storj-antonio approved these changes

2023-03-23 11:46 UTC, merged